#!/bin/sh

# Stamp each script with the latest commit that touched it
for script in scripts/*.ps1; do
  if grep -q 'Script:Revision' "$script"; then
    if git diff --cached --name-only | grep -q "$(basename "$script")"; then
      REV=$(git log -1 --format=%h -- "$script")
      sed -i '' "s/\$Script:Revision = \".*\"/\$Script:Revision = \"$REV\"/" "$script"
      git add "$script"
    fi
  fi
done
